[project]
name = "mcp-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.6.1",
    "python-logging-loki>=0.3.1",
    "pytz>=2025.2",
    "requests>=2.32.5",
]
